### ISSUE TITLE
[BUG]: app crashing 

### ISSUE THREAD

**Issue by saltsoftdrink** [rahul-gill/Self-Attendance-Tracker#22]
App is crashing after submitting a new course

**Comment by rahul-gill** [comment]
f droid build?

**Comment by saltsoftdrink** [comment]
> f droid build?

Yes

**Comment by rahul-gill** [comment]
I've made a lot of changes this week and it might take a week more to polish those changes. Then I'll update the app on f-droid. You can try out the [app from ci builds](https://github.com/rahul-gill/Self-Attendance-Tracker/actions/runs/8960406170) to see how it behaves on main branch.
