### ISSUE TITLE
Self Attendance at OpenApk

### ISSUE THREAD

**Issue by mobilenetworkltd** [rahul-gill/Self-Attendance-Tracker#39]
Hey,

I'm running a open source repo for Android apps at https://www.openapk.net and I would like to have Self Attendance listed in the repo. Please review the listing at https://www.openapk.net/self-attendance-tracker/com.github.rahul_gill.attendance/

It is hooked to your GitHub repo so all the updates are automatically pushed to OpenAPK. Let me know if its ok !

If you are interested you can link to it and use our download banners ( https://www.openapk.net/images/openapk-badge.png )
```
[<img src="https://www.openapk.net/images/openapk-badge.png" alt="Get it on OpenApk" height="80">](https://www.openapk.net/self-attendance-tracker/com.github.rahul_gill.attendance/)
```

**Comment by rahul-gill** [comment]
Added the banner
