### ISSUE TITLE
[BUG]: No mechanism to add status for older classes

### ISSUE THREAD

**Issue by Priyanshu-Prime** [rahul-gill/Self-Attendance-Tracker#44]
**Description**
If I install the app in the middle of the semester I have no means to mark the attendance for days which have already passed

**Expected behaviour**
The specific courses should have older dates mentioned to mark attendance for them.

**Smartphone (please complete the following information):**
 - Device: Motorola Edge 50 Fusion
 - OS: Android 14

**Comment by rahul-gill** [comment]
this is possible. Go to course details. Now there's two ways to add old classes details. Either (i) create an extra class for that or (ii) Click on a schedule item, then click on Add class on this schedule.
